name: Timestam action test
  
on:    
  workflow_dispatch:
  
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Get Timestamp Action
        id: timestamp
        uses: nanzm/get-time-action@v2.0
        with:
          format: 'MM/DD/YYYY HH:mm a'
          
      - name: Print result
        run: echo "${{ steps.timestamp.outputs.time }}"
