name: Timestam action test
  
on:    
  workflow_dispatch:
  
jobs:
  test-ubuntu:
    name: Test Ubuntu
    runs-on: ubuntu-latest
    
    steps:        
      - name: Set timestamp
        id: timestamp
        run: echo "time=$(date +'%m/%d/%Y %H:%M %p')" >> "$GITHUB_OUTPUT"
        
      - name: Print timestamp
        run: echo "${{ steps.timestamp.outputs.time }}"

  test-windows:
    name: Test Windows
    runs-on: windows-latest
    
    steps:        
      - name: Set timestamp
        id: timestamp
        run: echo "time=$(date +'%m/%d/%Y %H:%M %p')" >> "$GITHUB_OUTPUT"
        
      - name: Print timestamp
        run: echo "${{ steps.timestamp.outputs.time }}"

  test-macos:
    name: Test macOS
    runs-on: macos-latest
    
    steps:        
      - name: Set timestamp
        id: timestamp
        run: echo "time=$(date +'%m/%d/%Y %H:%M %p')" >> "$GITHUB_OUTPUT"
        
      - name: Print timestamp
        run: echo "${{ steps.timestamp.outputs.time }}"
