name: Timestam action test
  
on:    
  workflow_dispatch:
  
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:        
      - name: Set timestamp
        id: timestamp
        run: echo "{time}=(date +'%m/%d/%Y %H:%M %p')" >> $GITHUB_STATE
        
      - name: Print timestamp
        run: echo "{{ steps.timestamp.outputs.time }}"
